name: example
description: >
  A Navand app.
publish_to: none
environment:
  sdk: ^3.1.0
dependencies:
  navand:
    path: ../
dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
  lints: ^2.1.1
