name: example
description: >
  A Navand app.
publish_to: none
environment:
  sdk: ^3.2.3
dependencies:
  navand:
    path: ../
dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0
