include: package:lints/recommended.yaml
linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_final_parameters: true
    prefer_relative_imports: true
    avoid_print: true
    comment_references: true
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
