name: navand
description: >
  Navand is a web framework in Dart that lets developers create UIs with a
  widget model similar to Flutter. Navand apps are compiled into JS and painted
  using HTML & CSS.
version: 0.3.3
repository: https://github.com/Hawmex/navand
executables:
  navand:
environment:
  sdk: ^3.0.1
dev_dependencies:
  lints: ^2.1.1
dependencies:
  args: ^2.4.2
  js: ^0.6.7
