name: navand
description: >
  Navand is a web framework in Dart that lets developers create UIs with a
  widget model similar to Flutter. Navand apps are compiled into JS and painted
  using HTML & CSS.
version: 1.0.0-alpha.12
repository: https://github.com/Hawmex/navand
environment:
  sdk: ^3.1.0
dev_dependencies:
  lints: ^2.1.1
dependencies:
  js: ^0.6.7
